Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "Tequila")
Ingredient.create(name: "Rye")
Ingredient.create(name: "Bourbon")
Ingredient.create(name: "Angostura bitters")
Ingredient.create(name: "Sugar")
